### ISSUE TITLE
Error while running example.

### ISSUE THREAD

**Issue by 1729antony** [wasserfeder/lomap#2]
I get the following error while running the example. Is it due to any version compatibility ? Thanks.

Traceback (most recent call last):
  File "ijrr2013.py", line 226, in <module>
    main()
  File "ijrr2013.py", line 79, in main
    prefix_length, prefixes, suffix_cycle_cost, suffix_cycles = lomap.robust_multi_agent_optimal_run(ts_tuple, rhos, formula, opt_prop)
  File "/home/asus/.local/lib/python2.7/site-packages/lomap/algorithms/robust_multi_agent_optimal_run.py", line 67, in robust_multi_agent_optimal_run
    team_ts = ts_times_ts(ts_tuple)
  File "/home/asus/.local/lib/python2.7/site-packages/lomap/algorithms/product.py", line 171, in ts_times_ts
    product_ts.g.add_node(init_state, {'prop':init_prop, 'label':"%s\\n%s" % (init_state,list(init_prop))})
TypeError: add_node() takes exactly 2 arguments (3 given)

**Comment by wasserfeder** [comment]
What version of lomap are you running? The error seems to originate at a line that does not correspond to the latest version.
Also, your particular problem might be because of your networkx version. What version do you have installed?
Networkx did a lot of API changes from version 1.x to 2.0, and I haven't ported the code yet to the new version. The solution for now is to use networkx 1.11, the latest 1.x.

**Comment by 1729antony** [comment]
Hi, I was using the 2.1 version and reverted back to networkx 1.11 and lomap is running now. Thanks for that. Just saw that you mention the versions required in the setup file. Sorry that I did not read it before. Thanks again.
